version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  app:
    image: your-dockerhub-id/your-app:latest
    container_name: myapp
    ports:
      - "8081:8081"
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    depends_on:
      - elasticsearch