spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/myshop
    url: jdbc:h2:mem:myshop;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
#        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
#    org.hibernate.SQL: info
#    org.hibernate.type: trace #스프링 부트 2.x, hibernate5
#    org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6

jwt:
  secret: bXktc2VjcmV0LWtleS1teS1zZWNyZXQta2V5LW15LXNlY3JldC1rZXk=

server:
  port: 8081
  address: 0.0.0.0